FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ordersystem /app/cmd/ordersystem/main.go /app/cmd/ordersystem/wire_gen.go

FROM alpine:latest
WORKDIR /app
RUN apk add --no-cache bash
COPY wait-for-it.sh /usr/local/bin/wait-for-it
RUN chmod +x /usr/local/bin/wait-for-it
COPY --from=builder /app/ordersystem .
COPY .env /app/
CMD ["sh", "-c", "/usr/local/bin/wait-for-it rabbitmq:5672 -t 100 -- ./ordersystem"]