services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network

  migrator:
    build: 
      context: .
      dockerfile: Dockerfile.migration
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: orders
    networks:
      - app-network

  order-system:
    build:
      context: .
      dockerfile: Dockerfile.ordersystem
    depends_on:
      - migrator
      - rabbitmq
      - mysql
    ports:
      - 8080:8080
      - 50051:50051
      - 8001:8001
    networks:
      - app-network

networks:
  app-network:
    driver: bridge